[assembly: System.Reflection.AssemblyCompany("Radu Hociung")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2021 Radu Hociung")]
[assembly: System.Reflection.AssemblyDescription("Auto-installs the Harmony Mod Manager")]
[assembly: System.Reflection.AssemblyProduct(HarmonyManager.Versioning.PACKAGE_NAME)]
[assembly: System.Reflection.AssemblyTitle("Lib.Harmony Helper for Cities: Skylines")]
